export const environment = {
    production: true,
    POSTGRES_URL: "postgres://postgres.znolxmhnrvlyuyvzgzyf:RPH6TUy5x3ZnlW8R@aws-1-us-east-1.pooler.supabase.com:6543/postgres?sslmode=require&supa=base-pooler.x",
    POSTGRES_USER: "postgres",
    POSTGRES_HOST: "db.znolxmhnrvlyuyvzgzyf.supabase.co",
    SUPABASE_JWT_SECRET:"/mPthHzp/GM9n4/2GUcOPQ5dSwEOoJYlWzfdDOie+2QY9G+3zrNgeyO/4jP1gAHwNhTbEMkS0hvonWn0uvY55g==",
    POSTGRES_PRISMA_URL:"postgres://postgres.znolxmhnrvlyuyvzgzyf:RPH6TUy5x3ZnlW8R@aws-1-us-east-1.pooler.supabase.com:6543/postgres?sslmode=require&pgbouncer=true",
    POSTGRES_PASSWORD: "RPH6TUy5x3ZnlW8R",
    POSTGRES_DATABASE: "postgres",
    PORFOLIO_PUBLIC_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpub2x4bWhucnZseXV5dnpnenlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMDgzNDcsImV4cCI6MjA3Mzg4NDM0N30.ZlRidhoBiyVwcwiQYXMA7n_ucTksTv0MQO6dAHY7tbg",
    SUPABASE_URL: "https://znolxmhnrvlyuyvzgzyf.supabase.co",
    SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpub2x4bWhucnZseXV5dnpnenlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMDgzNDcsImV4cCI6MjA3Mzg4NDM0N30.ZlRidhoBiyVwcwiQYXMA7n_ucTksTv0MQO6dAHY7tbg",  
    SUPABASE_SERVICE_ROLE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpub2x4bWhucnZseXV5dnpnenlmIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1ODMwODM0NywiZXhwIjoyMDczODg0MzQ3fQ.QROfQODxLi7o5O0kY03f_bAc77OoU7USglk4KHapoWI",
    POSTGRES_URL_NON_POOLING: "postgres://postgres.znolxmhnrvlyuyvzgzyf:RPH6TUy5x3ZnlW8R@aws-1-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require",
    PORFOLIO_PUBLIC_SUPABASE_URL: "https://znolxmhnrvlyuyvzgzyf.supabase.co",
};
